"""
data_generation.py
===================
PatientTriage.ai — Synthetic Patient Data Generator

IMPORTANT / HONESTY NOTICE
---------------------------
This module produces SYNTHETIC / SIMULATED patient data only.
No real patient data, and no real clinical dataset (e.g. MIMIC-IV-ED), is
used anywhere in this prototype. The labels below are generated by a
deterministic, documented RULE-BASED LABELING FUNCTION (see
`assign_label_and_reason`) written to loosely follow the *publicly
published logic* of the Emergency Severity Index (ESI) — NOT from any
clinical outcome data, NOT clinically validated, and NOT reviewed by a
clinician. Treat this data, and any model trained on it, as a
methodology demonstration only.

Why synthetic data, and why this labeling approach:
  - No real ED dataset (e.g. MIMIC-IV-ED) is available in this sandboxed
    environment (no PhysioNet credentialed access, no network access to
    non-package-registry domains).
  - The pipeline below is written so that if a real, properly licensed
    dataset (e.g. MIMIC-IV-ED, credentialed via PhysioNet) is later
    plugged in, `preprocessing.py` and both models can be retrained
    against it with minimal changes (see `load_real_dataset()` stub).

The generator is fully deterministic given a random seed (numpy
`Generator`), so the same seed always reproduces the same dataset —
required for a reproducible hackathon demo.
"""

from __future__ import annotations
import numpy as np
import pandas as pd
from dataclasses import dataclass, field
from typing import Optional

from .age_bands import age_band as _shared_age_band

RANDOM_SEED = 42

CHIEF_COMPLAINTS = {
    "critical": [
        "crushing chest pain radiating to left arm", "sudden difficulty breathing",
        "unresponsive, found on floor", "severe uncontrolled bleeding from laceration",
        "stroke-like symptoms, facial droop and slurred speech", "severe allergic reaction with facial swelling",
        "witnessed seizure, now confused", "gunshot wound", "severe head trauma after fall",
    ],
    "emergent": [
        "chest pain, worse with exertion", "shortness of breath at rest",
        "high fever with confusion", "severe abdominal pain, sudden onset",
        "signs of infection with rapid heart rate", "moderate bleeding, not controlled",
        "new onset severe headache, worst of life", "asthma attack, not improving with inhaler",
    ],
    "urgent": [
        "moderate abdominal pain", "persistent vomiting and diarrhea",
        "possible broken bone after fall", "worsening cough and fever for 3 days",
        "moderate laceration needing sutures", "migraine not responding to home treatment",
        "urinary tract infection symptoms", "back pain after lifting heavy object",
    ],
    "less_urgent": [
        "mild sore throat", "minor ankle sprain", "rash, no other symptoms",
        "mild ear pain", "cold symptoms for 2 days", "minor cut, bleeding controlled",
        "prescription refill needed", "mild low back pain, chronic",
    ],
    "non_urgent": [
        "requesting medication refill", "mild cold symptoms", "routine wound check",
        "follow-up on stable chronic condition", "minor bruise", "mild seasonal allergies",
    ],
}

HISTORY_SNIPPETS = [
    "hypertension", "type 2 diabetes", "asthma", "prior myocardial infarction",
    "COPD", "chronic kidney disease", "no significant past medical history",
    "seasonal allergies only", "prior stroke", "atrial fibrillation on blood thinners",
    "pregnancy, second trimester", "immunocompromised, on chemotherapy",
]


@dataclass
class VitalRanges:
    """Age-band-specific 'typical' physiological ranges used only to make
    synthetic data age-aware. These are simplified prototype heuristics,
    not medical guidelines."""
    hr: tuple
    rr: tuple
    sbp: tuple
    dbp: tuple
    spo2: tuple
    temp: tuple


AGE_BAND_RANGES = {
    "pediatric": VitalRanges(hr=(90, 140), rr=(20, 30), sbp=(85, 110), dbp=(50, 70), spo2=(96, 100), temp=(36.5, 38.5)),
    "adult": VitalRanges(hr=(60, 100), rr=(12, 20), sbp=(100, 130), dbp=(65, 85), spo2=(96, 100), temp=(36.3, 37.5)),
    "geriatric": VitalRanges(hr=(55, 95), rr=(12, 22), sbp=(105, 145), dbp=(65, 90), spo2=(94, 99), temp=(36.0, 37.6)),
}


def age_band(age: float) -> str:
    # delegates to the single shared definition in age_bands.py so
    # data generation, preprocessing, and safety rules never disagree
    return _shared_age_band(age)


def sample_normal_vitals(rng: np.random.Generator, age: float) -> dict:
    band = AGE_BAND_RANGES[age_band(age)]
    return {
        "heart_rate": round(rng.uniform(*band.hr), 0),
        "resp_rate": round(rng.uniform(*band.rr), 0),
        "sbp": round(rng.uniform(*band.sbp), 0),
        "dbp": round(rng.uniform(*band.dbp), 0),
        "spo2": round(rng.uniform(*band.spo2), 0),
        "temperature": round(rng.uniform(*band.temp), 1),
    }


def perturb_toward_severity(vitals: dict, severity: str, rng: np.random.Generator, age: float) -> dict:
    """Push vitals toward physiologically 'sicker' values as severity
    increases. This is a simplified, clearly-labeled prototype heuristic
    (not a validated physiological model)."""
    v = dict(vitals)
    band = age_band(age)
    severity_scale = {"critical": 1.0, "emergent": 0.7, "urgent": 0.35, "less_urgent": 0.1, "non_urgent": 0.0}
    s = severity_scale[severity] * rng.uniform(0.7, 1.15)

    v["heart_rate"] += s * rng.uniform(25, 70) * rng.choice([-1, 1], p=[0.25, 0.75])
    v["resp_rate"] += s * rng.uniform(6, 20)
    v["sbp"] -= s * rng.uniform(15, 55) * rng.choice([1, -0.3], p=[0.75, 0.25])
    v["spo2"] -= s * rng.uniform(3, 20)
    v["temperature"] += s * rng.uniform(0.3, 2.2) * rng.choice([1, -1], p=[0.85, 0.15])

    # clip to plausible physiological bounds
    v["heart_rate"] = float(np.clip(v["heart_rate"], 30, 220))
    v["resp_rate"] = float(np.clip(v["resp_rate"], 4, 60))
    v["sbp"] = float(np.clip(v["sbp"], 40, 220))
    v["dbp"] = float(np.clip(v["dbp"], 20, 140))
    v["spo2"] = float(np.clip(v["spo2"], 55, 100))
    v["temperature"] = float(np.clip(v["temperature"], 33.5, 41.5))
    for k in v:
        v[k] = round(v[k], 1)
    return v


def assign_label_and_reason(row: dict) -> tuple:
    """
    Deterministic, documented rule-based ESI labeling function used ONLY to
    generate synthetic training labels. Loosely inspired by publicly
    described ESI decision logic (danger signs -> resource needs -> vitals),
    simplified for a prototype. NOT a clinical algorithm and NOT validated.

    Returns (esi_level:int, reason:str)
    """
    danger_signs = row.get("_danger_signs", False)
    severity = row["_severity_tag"]

    hr, rr, sbp, spo2, temp = row["heart_rate"], row["resp_rate"], row["sbp"], row["spo2"], row["temperature"]
    age = row["age"]
    band = age_band(age)

    # Immediate life-threat -> ESI 1
    if danger_signs or spo2 < 85 or sbp < 70 or rr < 6 or rr > 45 or hr > 180 or hr < 35:
        return 1, "Danger signs / severely abnormal vitals meeting immediate-resuscitation criteria."

    if severity == "critical":
        return 1 if spo2 < 90 or sbp < 80 else 2, "High-risk chief complaint with markedly abnormal vitals."

    if severity == "emergent":
        return 2, "Emergent-pattern chief complaint with significantly abnormal vitals."

    if severity == "urgent":
        # if vitals are actually quite abnormal despite "urgent" complaint text, bump up
        if spo2 < 92 or sbp < 90 or hr > 130:
            return 2, "Urgent complaint but vitals more consistent with higher acuity (symptom/vital mismatch)."
        return 3, "Urgent chief complaint, vitals within moderately abnormal range; multiple resources likely needed."

    if severity == "less_urgent":
        if spo2 < 94 or hr > 120:
            return 3, "Less-urgent complaint but vitals more abnormal than expected (symptom/vital mismatch)."
        return 4, "Minor complaint, one resource likely needed, vitals near normal."

    # non_urgent
    if spo2 < 95 or hr > 110 or temp > 38.5:
        return 3, "Non-urgent complaint but vitals show unexpected abnormality (symptom/vital mismatch)."
    return 5, "Routine/non-urgent complaint, normal vitals, no resources anticipated."


def maybe_drop(value, rng: np.random.Generator, p: float):
    return None if rng.random() < p else value


def generate_patient(rng: np.random.Generator, patient_id: str, force_case: Optional[str] = None) -> dict:
    """Generate a single synthetic patient record. `force_case` can pin a
    specific demonstration category (see demo_patients.py)."""

    case = force_case or rng.choice(
        ["normal", "critical", "ambiguous", "pediatric", "geriatric", "zero_history",
         "missing_vitals", "missing_history", "vital_symptom_mismatch_high", "vital_symptom_mismatch_low"],
        p=[0.30, 0.10, 0.10, 0.10, 0.10, 0.08, 0.08, 0.06, 0.04, 0.04],
    )

    # ---- age ----
    if case == "pediatric":
        age = rng.integers(1, 13)
    elif case == "geriatric":
        age = rng.integers(65, 95)
    else:
        age = rng.integers(13, 90)

    # ---- severity tag (drives label + text) ----
    if case == "critical":
        severity = rng.choice(["critical", "emergent"], p=[0.7, 0.3])
    elif case == "ambiguous":
        severity = rng.choice(["urgent", "emergent"], p=[0.5, 0.5])
    elif case in ("vital_symptom_mismatch_high",):
        severity = "less_urgent"  # mild-sounding complaint, we'll push vitals bad
    elif case in ("vital_symptom_mismatch_low",):
        severity = "emergent"  # scary-sounding complaint, we'll keep vitals near-normal
    else:
        severity = rng.choice(
            ["critical", "emergent", "urgent", "less_urgent", "non_urgent"],
            p=[0.05, 0.12, 0.28, 0.30, 0.25],
        )

    danger_signs = case == "critical" and rng.random() < 0.5

    base_vitals = sample_normal_vitals(rng, age)
    if case == "vital_symptom_mismatch_low":
        vitals = base_vitals  # keep normal despite scary complaint text
    else:
        vitals = perturb_toward_severity(base_vitals, severity, rng, age)

    if case == "vital_symptom_mismatch_high":
        # force vitals bad regardless of mild complaint text
        vitals = perturb_toward_severity(base_vitals, "emergent", rng, age)

    complaint = rng.choice(CHIEF_COMPLAINTS[severity])
    n_symptoms = rng.integers(0, 3)
    symptom_pool = [c for lst in CHIEF_COMPLAINTS.values() for c in lst if c != complaint]
    symptoms = list(rng.choice(symptom_pool, size=n_symptoms, replace=False)) if n_symptoms > 0 else []

    if case == "zero_history":
        history = "no prior medical history (first-time patient)"
        has_history = 1  # explicitly known: patient genuinely has none (confirmed absence, not "unavailable")
    elif case == "missing_history":
        history = None
        has_history = 0  # explicitly "not available" — set later in the missingness block too
    else:
        # Reference parameter from the Round 2 brief: "assume mixed data
        # availability — roughly half of arriving patients have some
        # prior health record on file, half do not." We approximate that
        # ~50/50 split here across the general patient population (outside
        # the explicitly-forced zero_history / missing_history demo cases).
        has_prior_record_on_file = rng.random() < 0.5
        if has_prior_record_on_file:
            n_hist = rng.integers(0, 3)
            history = ("; ".join(rng.choice(HISTORY_SNIPPETS, size=n_hist, replace=False))
                       if n_hist > 0 else "no significant past medical history")
            has_history = 1
        else:
            history = None
            has_history = 0

    pain = int(np.clip(rng.integers(0, 11) if severity in ("less_urgent", "non_urgent")
                        else rng.integers(3, 11), 0, 10))

    record = {
        "patient_id": patient_id,
        "age": int(age),
        "heart_rate": vitals["heart_rate"],
        "resp_rate": vitals["resp_rate"],
        "sbp": vitals["sbp"],
        "dbp": vitals["dbp"],
        "spo2": vitals["spo2"],
        "temperature": vitals["temperature"],
        "pain_score": pain,
        "chief_complaint": complaint,
        "symptoms": "; ".join(symptoms) if symptoms else "none reported",
        "history": history,
        "has_history_info": has_history,
        "_severity_tag": severity,
        "_danger_signs": danger_signs,
        "_case_category": case,
    }

    # ---- missingness ----
    if case == "missing_vitals":
        drop_field = rng.choice(["sbp", "dbp", "spo2", "resp_rate"])
        record[drop_field] = None
    # (missing_history case already has history=None / has_history_info=0 set above)
    # small baseline chance of incidental missingness elsewhere for realism
    for f in ["sbp", "dbp", "spo2", "resp_rate", "temperature", "pain_score"]:
        if case not in ("missing_vitals",) and rng.random() < 0.03:
            record[f] = None

    esi, reason = assign_label_and_reason({**record,
                                            "heart_rate": record["heart_rate"] or 90,
                                            "resp_rate": record["resp_rate"] or 16,
                                            "sbp": record["sbp"] or 115,
                                            "spo2": record["spo2"] or 98,
                                            "temperature": record["temperature"] or 37.0})
    record["esi_label"] = esi
    record["label_reason"] = reason
    return record


def generate_dataset(n: int = 2000, seed: int = RANDOM_SEED) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    records = [generate_patient(rng, f"SYN-{i:05d}") for i in range(n)]
    df = pd.DataFrame(records)
    return df


def load_real_dataset(path: Optional[str] = None) -> Optional[pd.DataFrame]:
    """
    Stub for plugging in a real, properly licensed dataset such as
    MIMIC-IV-ED (requires credentialed PhysioNet access — NOT available in
    this sandboxed prototype environment). If `path` is provided and
    exists, this would load and column-map it to the same schema as
    `generate_dataset()`. Returns None in this prototype since no real
    dataset is available.
    """
    return None


if __name__ == "__main__":
    df = generate_dataset(2000)
    df.to_csv("/home/claude/patienttriage/data/synthetic/synthetic_patients.csv", index=False)
    print(f"Generated {len(df)} synthetic patients")
    print(df["esi_label"].value_counts().sort_index())
    print(df["_case_category"].value_counts())
